### ISSUE TITLE
Most code should be colorspace agnostic

### ISSUE THREAD

**Issue by THEjoezack** [colormine/colormine#3]
We probably need to switch over to one color class, the calling code shouldn't have to worry about how to get the correct color space or have to choose which ones to report.

**Comment by ghost** [comment]
I think this is almost complete?  I would like to hide some of the details of the conversions and then mark this complete... what do you think @THEjoezack ?

**Comment by THEjoezack** [comment]
Looks great!

I removed a couple extra methods that ColorProfiles were using, and the servlets only ever pass colors.

I really wish that java had something like "assembly" accessibility. It's unfortunate that the Rgb\Lab\Xyz etc are still visible, but I don't think there's much we can do about except 'remember' not to use them. Blech.

Closed!

**Comment by ghost** [comment]
Cool, I'm trying to get Rgb completely. It cleans things up a bunch
not having to convert form Rgb to color and back everywhere.

Caught a few bugs with the unit test already, glad we have them !

Sent from my iPhone

On Mar 2, 2012, at 10:43 PM, Joe Zack
reply@reply.github.com
wrote:
