### ISSUE TITLE
True Unit Tests

### ISSUE THREAD

**Issue by THEjoezack** [colormine/colormine#8]
Since the core of ColorMine is just a library, we should have good "unit" tests for it.

These tests should ensure that the results are accurate and that we have a user-friendly API. If it's not easily testable, than it's not easily usable!

**Comment by ghost** [comment]
Working on unit test. moved to new test framework, TestNG. Changing Test name to conform to standard. MethodName_Givenparamaters_expectedResult.

**Comment by THEjoezack** [comment]
Great job! I'm loving TestNG and mockito!
