### ISSUE TITLE
Pick a license!

### ISSUE THREAD

**Issue by THEjoezack** [colormine/colormine#9]
Creative Commons?
ASF?
GPL?
WTFPL?

http://www.codinghorror.com/blog/2007/04/pick-a-license-any-license.html
http://three.org/openart/license_chooser/

**Comment by ghost** [comment]
it seems like BSD or MIT would suit our needs.  Was there one you where leaning towards?

**Comment by THEjoezack** [comment]
No preference really. Pick one! :)

**Comment by ghost** [comment]
my vote would be to use the MIT.

**Comment by THEjoezack** [comment]
Done!
